// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oscar

import (
	"context"

	"github.com/pchchv/go-icq/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockBuddyListRegistry creates a new instance of mockBuddyListRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBuddyListRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBuddyListRegistry {
	mock := &mockBuddyListRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockBuddyListRegistry is an autogenerated mock type for the BuddyListRegistry type
type mockBuddyListRegistry struct {
	mock.Mock
}

type mockBuddyListRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBuddyListRegistry) EXPECT() *mockBuddyListRegistry_Expecter {
	return &mockBuddyListRegistry_Expecter{mock: &_m.Mock}
}

// ClearBuddyListRegistry provides a mock function for the type mockBuddyListRegistry
func (_mock *mockBuddyListRegistry) ClearBuddyListRegistry(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearBuddyListRegistry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyListRegistry_ClearBuddyListRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearBuddyListRegistry'
type mockBuddyListRegistry_ClearBuddyListRegistry_Call struct {
	*mock.Call
}

// ClearBuddyListRegistry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockBuddyListRegistry_Expecter) ClearBuddyListRegistry(ctx interface{}) *mockBuddyListRegistry_ClearBuddyListRegistry_Call {
	return &mockBuddyListRegistry_ClearBuddyListRegistry_Call{Call: _e.mock.On("ClearBuddyListRegistry", ctx)}
}

func (_c *mockBuddyListRegistry_ClearBuddyListRegistry_Call) Run(run func(ctx context.Context)) *mockBuddyListRegistry_ClearBuddyListRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockBuddyListRegistry_ClearBuddyListRegistry_Call) Return(err error) *mockBuddyListRegistry_ClearBuddyListRegistry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyListRegistry_ClearBuddyListRegistry_Call) RunAndReturn(run func(ctx context.Context) error) *mockBuddyListRegistry_ClearBuddyListRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterBuddyList provides a mock function for the type mockBuddyListRegistry
func (_mock *mockBuddyListRegistry) RegisterBuddyList(ctx context.Context, user state.IdentScreenName) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for RegisterBuddyList")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyListRegistry_RegisterBuddyList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterBuddyList'
type mockBuddyListRegistry_RegisterBuddyList_Call struct {
	*mock.Call
}

// RegisterBuddyList is a helper method to define mock.On call
//   - ctx context.Context
//   - user state.IdentScreenName
func (_e *mockBuddyListRegistry_Expecter) RegisterBuddyList(ctx interface{}, user interface{}) *mockBuddyListRegistry_RegisterBuddyList_Call {
	return &mockBuddyListRegistry_RegisterBuddyList_Call{Call: _e.mock.On("RegisterBuddyList", ctx, user)}
}

func (_c *mockBuddyListRegistry_RegisterBuddyList_Call) Run(run func(ctx context.Context, user state.IdentScreenName)) *mockBuddyListRegistry_RegisterBuddyList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockBuddyListRegistry_RegisterBuddyList_Call) Return(err error) *mockBuddyListRegistry_RegisterBuddyList_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyListRegistry_RegisterBuddyList_Call) RunAndReturn(run func(ctx context.Context, user state.IdentScreenName) error) *mockBuddyListRegistry_RegisterBuddyList_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterBuddyList provides a mock function for the type mockBuddyListRegistry
func (_mock *mockBuddyListRegistry) UnregisterBuddyList(ctx context.Context, user state.IdentScreenName) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterBuddyList")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyListRegistry_UnregisterBuddyList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterBuddyList'
type mockBuddyListRegistry_UnregisterBuddyList_Call struct {
	*mock.Call
}

// UnregisterBuddyList is a helper method to define mock.On call
//   - ctx context.Context
//   - user state.IdentScreenName
func (_e *mockBuddyListRegistry_Expecter) UnregisterBuddyList(ctx interface{}, user interface{}) *mockBuddyListRegistry_UnregisterBuddyList_Call {
	return &mockBuddyListRegistry_UnregisterBuddyList_Call{Call: _e.mock.On("UnregisterBuddyList", ctx, user)}
}

func (_c *mockBuddyListRegistry_UnregisterBuddyList_Call) Run(run func(ctx context.Context, user state.IdentScreenName)) *mockBuddyListRegistry_UnregisterBuddyList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockBuddyListRegistry_UnregisterBuddyList_Call) Return(err error) *mockBuddyListRegistry_UnregisterBuddyList_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyListRegistry_UnregisterBuddyList_Call) RunAndReturn(run func(ctx context.Context, user state.IdentScreenName) error) *mockBuddyListRegistry_UnregisterBuddyList_Call {
	_c.Call.Return(run)
	return _c
}
