// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oscar

import (
	"context"

	"github.com/pchchv/go-icq/state"
	"github.com/pchchv/go-icq/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockPermitDenyService creates a new instance of mockPermitDenyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPermitDenyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPermitDenyService {
	mock := &mockPermitDenyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPermitDenyService is an autogenerated mock type for the PermitDenyService type
type mockPermitDenyService struct {
	mock.Mock
}

type mockPermitDenyService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPermitDenyService) EXPECT() *mockPermitDenyService_Expecter {
	return &mockPermitDenyService_Expecter{mock: &_m.Mock}
}

// AddDenyListEntries provides a mock function for the type mockPermitDenyService
func (_mock *mockPermitDenyService) AddDenyListEntries(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x07_PermitDenyAddDenyListEntries) error {
	ret := _mock.Called(ctx, instance, inBody)

	if len(ret) == 0 {
		panic("no return value specified for AddDenyListEntries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNAC_0x09_0x07_PermitDenyAddDenyListEntries) error); ok {
		r0 = returnFunc(ctx, instance, inBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPermitDenyService_AddDenyListEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDenyListEntries'
type mockPermitDenyService_AddDenyListEntries_Call struct {
	*mock.Call
}

// AddDenyListEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inBody wire.SNAC_0x09_0x07_PermitDenyAddDenyListEntries
func (_e *mockPermitDenyService_Expecter) AddDenyListEntries(ctx interface{}, instance interface{}, inBody interface{}) *mockPermitDenyService_AddDenyListEntries_Call {
	return &mockPermitDenyService_AddDenyListEntries_Call{Call: _e.mock.On("AddDenyListEntries", ctx, instance, inBody)}
}

func (_c *mockPermitDenyService_AddDenyListEntries_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x07_PermitDenyAddDenyListEntries)) *mockPermitDenyService_AddDenyListEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNAC_0x09_0x07_PermitDenyAddDenyListEntries
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x09_0x07_PermitDenyAddDenyListEntries)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockPermitDenyService_AddDenyListEntries_Call) Return(err error) *mockPermitDenyService_AddDenyListEntries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPermitDenyService_AddDenyListEntries_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x07_PermitDenyAddDenyListEntries) error) *mockPermitDenyService_AddDenyListEntries_Call {
	_c.Call.Return(run)
	return _c
}

// AddPermListEntries provides a mock function for the type mockPermitDenyService
func (_mock *mockPermitDenyService) AddPermListEntries(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x05_PermitDenyAddPermListEntries) error {
	ret := _mock.Called(ctx, instance, inBody)

	if len(ret) == 0 {
		panic("no return value specified for AddPermListEntries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNAC_0x09_0x05_PermitDenyAddPermListEntries) error); ok {
		r0 = returnFunc(ctx, instance, inBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPermitDenyService_AddPermListEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPermListEntries'
type mockPermitDenyService_AddPermListEntries_Call struct {
	*mock.Call
}

// AddPermListEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inBody wire.SNAC_0x09_0x05_PermitDenyAddPermListEntries
func (_e *mockPermitDenyService_Expecter) AddPermListEntries(ctx interface{}, instance interface{}, inBody interface{}) *mockPermitDenyService_AddPermListEntries_Call {
	return &mockPermitDenyService_AddPermListEntries_Call{Call: _e.mock.On("AddPermListEntries", ctx, instance, inBody)}
}

func (_c *mockPermitDenyService_AddPermListEntries_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x05_PermitDenyAddPermListEntries)) *mockPermitDenyService_AddPermListEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNAC_0x09_0x05_PermitDenyAddPermListEntries
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x09_0x05_PermitDenyAddPermListEntries)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockPermitDenyService_AddPermListEntries_Call) Return(err error) *mockPermitDenyService_AddPermListEntries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPermitDenyService_AddPermListEntries_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x05_PermitDenyAddPermListEntries) error) *mockPermitDenyService_AddPermListEntries_Call {
	_c.Call.Return(run)
	return _c
}

// DelDenyListEntries provides a mock function for the type mockPermitDenyService
func (_mock *mockPermitDenyService) DelDenyListEntries(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x08_PermitDenyDelDenyListEntries) error {
	ret := _mock.Called(ctx, instance, inBody)

	if len(ret) == 0 {
		panic("no return value specified for DelDenyListEntries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNAC_0x09_0x08_PermitDenyDelDenyListEntries) error); ok {
		r0 = returnFunc(ctx, instance, inBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPermitDenyService_DelDenyListEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelDenyListEntries'
type mockPermitDenyService_DelDenyListEntries_Call struct {
	*mock.Call
}

// DelDenyListEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inBody wire.SNAC_0x09_0x08_PermitDenyDelDenyListEntries
func (_e *mockPermitDenyService_Expecter) DelDenyListEntries(ctx interface{}, instance interface{}, inBody interface{}) *mockPermitDenyService_DelDenyListEntries_Call {
	return &mockPermitDenyService_DelDenyListEntries_Call{Call: _e.mock.On("DelDenyListEntries", ctx, instance, inBody)}
}

func (_c *mockPermitDenyService_DelDenyListEntries_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x08_PermitDenyDelDenyListEntries)) *mockPermitDenyService_DelDenyListEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNAC_0x09_0x08_PermitDenyDelDenyListEntries
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x09_0x08_PermitDenyDelDenyListEntries)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockPermitDenyService_DelDenyListEntries_Call) Return(err error) *mockPermitDenyService_DelDenyListEntries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPermitDenyService_DelDenyListEntries_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x08_PermitDenyDelDenyListEntries) error) *mockPermitDenyService_DelDenyListEntries_Call {
	_c.Call.Return(run)
	return _c
}

// DelPermListEntries provides a mock function for the type mockPermitDenyService
func (_mock *mockPermitDenyService) DelPermListEntries(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x06_PermitDenyDelPermListEntries) error {
	ret := _mock.Called(ctx, instance, inBody)

	if len(ret) == 0 {
		panic("no return value specified for DelPermListEntries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNAC_0x09_0x06_PermitDenyDelPermListEntries) error); ok {
		r0 = returnFunc(ctx, instance, inBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPermitDenyService_DelPermListEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelPermListEntries'
type mockPermitDenyService_DelPermListEntries_Call struct {
	*mock.Call
}

// DelPermListEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inBody wire.SNAC_0x09_0x06_PermitDenyDelPermListEntries
func (_e *mockPermitDenyService_Expecter) DelPermListEntries(ctx interface{}, instance interface{}, inBody interface{}) *mockPermitDenyService_DelPermListEntries_Call {
	return &mockPermitDenyService_DelPermListEntries_Call{Call: _e.mock.On("DelPermListEntries", ctx, instance, inBody)}
}

func (_c *mockPermitDenyService_DelPermListEntries_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x06_PermitDenyDelPermListEntries)) *mockPermitDenyService_DelPermListEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNAC_0x09_0x06_PermitDenyDelPermListEntries
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x09_0x06_PermitDenyDelPermListEntries)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockPermitDenyService_DelPermListEntries_Call) Return(err error) *mockPermitDenyService_DelPermListEntries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPermitDenyService_DelPermListEntries_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x09_0x06_PermitDenyDelPermListEntries) error) *mockPermitDenyService_DelPermListEntries_Call {
	_c.Call.Return(run)
	return _c
}

// RightsQuery provides a mock function for the type mockPermitDenyService
func (_mock *mockPermitDenyService) RightsQuery(ctx context.Context, inFrame wire.SNACFrame) wire.SNACMessage {
	ret := _mock.Called(ctx, inFrame)

	if len(ret) == 0 {
		panic("no return value specified for RightsQuery")
	}

	var r0 wire.SNACMessage
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNACFrame) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, inFrame)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	return r0
}

// mockPermitDenyService_RightsQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RightsQuery'
type mockPermitDenyService_RightsQuery_Call struct {
	*mock.Call
}

// RightsQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - inFrame wire.SNACFrame
func (_e *mockPermitDenyService_Expecter) RightsQuery(ctx interface{}, inFrame interface{}) *mockPermitDenyService_RightsQuery_Call {
	return &mockPermitDenyService_RightsQuery_Call{Call: _e.mock.On("RightsQuery", ctx, inFrame)}
}

func (_c *mockPermitDenyService_RightsQuery_Call) Run(run func(ctx context.Context, inFrame wire.SNACFrame)) *mockPermitDenyService_RightsQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.SNACFrame
		if args[1] != nil {
			arg1 = args[1].(wire.SNACFrame)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPermitDenyService_RightsQuery_Call) Return(sNACMessage wire.SNACMessage) *mockPermitDenyService_RightsQuery_Call {
	_c.Call.Return(sNACMessage)
	return _c
}

func (_c *mockPermitDenyService_RightsQuery_Call) RunAndReturn(run func(ctx context.Context, inFrame wire.SNACFrame) wire.SNACMessage) *mockPermitDenyService_RightsQuery_Call {
	_c.Call.Return(run)
	return _c
}
