// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oscar

import (
	"context"

	"github.com/pchchv/go-icq/state"
	"github.com/pchchv/go-icq/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockBuddyService creates a new instance of mockBuddyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBuddyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBuddyService {
	mock := &mockBuddyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockBuddyService is an autogenerated mock type for the BuddyService type
type mockBuddyService struct {
	mock.Mock
}

type mockBuddyService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBuddyService) EXPECT() *mockBuddyService_Expecter {
	return &mockBuddyService_Expecter{mock: &_m.Mock}
}

// AddBuddies provides a mock function for the type mockBuddyService
func (_mock *mockBuddyService) AddBuddies(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x04_BuddyAddBuddies) error {
	ret := _mock.Called(ctx, instance, inBody)

	if len(ret) == 0 {
		panic("no return value specified for AddBuddies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNAC_0x03_0x04_BuddyAddBuddies) error); ok {
		r0 = returnFunc(ctx, instance, inBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyService_AddBuddies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBuddies'
type mockBuddyService_AddBuddies_Call struct {
	*mock.Call
}

// AddBuddies is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inBody wire.SNAC_0x03_0x04_BuddyAddBuddies
func (_e *mockBuddyService_Expecter) AddBuddies(ctx interface{}, instance interface{}, inBody interface{}) *mockBuddyService_AddBuddies_Call {
	return &mockBuddyService_AddBuddies_Call{Call: _e.mock.On("AddBuddies", ctx, instance, inBody)}
}

func (_c *mockBuddyService_AddBuddies_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x04_BuddyAddBuddies)) *mockBuddyService_AddBuddies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNAC_0x03_0x04_BuddyAddBuddies
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x03_0x04_BuddyAddBuddies)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockBuddyService_AddBuddies_Call) Return(err error) *mockBuddyService_AddBuddies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyService_AddBuddies_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x04_BuddyAddBuddies) error) *mockBuddyService_AddBuddies_Call {
	_c.Call.Return(run)
	return _c
}

// AddTempBuddies provides a mock function for the type mockBuddyService
func (_mock *mockBuddyService) AddTempBuddies(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x0F_BuddyAddTempBuddies) error {
	ret := _mock.Called(ctx, instance, inBody)

	if len(ret) == 0 {
		panic("no return value specified for AddTempBuddies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNAC_0x03_0x0F_BuddyAddTempBuddies) error); ok {
		r0 = returnFunc(ctx, instance, inBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyService_AddTempBuddies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTempBuddies'
type mockBuddyService_AddTempBuddies_Call struct {
	*mock.Call
}

// AddTempBuddies is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inBody wire.SNAC_0x03_0x0F_BuddyAddTempBuddies
func (_e *mockBuddyService_Expecter) AddTempBuddies(ctx interface{}, instance interface{}, inBody interface{}) *mockBuddyService_AddTempBuddies_Call {
	return &mockBuddyService_AddTempBuddies_Call{Call: _e.mock.On("AddTempBuddies", ctx, instance, inBody)}
}

func (_c *mockBuddyService_AddTempBuddies_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x0F_BuddyAddTempBuddies)) *mockBuddyService_AddTempBuddies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNAC_0x03_0x0F_BuddyAddTempBuddies
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x03_0x0F_BuddyAddTempBuddies)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockBuddyService_AddTempBuddies_Call) Return(err error) *mockBuddyService_AddTempBuddies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyService_AddTempBuddies_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x0F_BuddyAddTempBuddies) error) *mockBuddyService_AddTempBuddies_Call {
	_c.Call.Return(run)
	return _c
}

// DelBuddies provides a mock function for the type mockBuddyService
func (_mock *mockBuddyService) DelBuddies(context1 context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x05_BuddyDelBuddies) error {
	ret := _mock.Called(context1, instance, inBody)

	if len(ret) == 0 {
		panic("no return value specified for DelBuddies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNAC_0x03_0x05_BuddyDelBuddies) error); ok {
		r0 = returnFunc(context1, instance, inBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyService_DelBuddies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelBuddies'
type mockBuddyService_DelBuddies_Call struct {
	*mock.Call
}

// DelBuddies is a helper method to define mock.On call
//   - context1 context.Context
//   - instance *state.SessionInstance
//   - inBody wire.SNAC_0x03_0x05_BuddyDelBuddies
func (_e *mockBuddyService_Expecter) DelBuddies(context1 interface{}, instance interface{}, inBody interface{}) *mockBuddyService_DelBuddies_Call {
	return &mockBuddyService_DelBuddies_Call{Call: _e.mock.On("DelBuddies", context1, instance, inBody)}
}

func (_c *mockBuddyService_DelBuddies_Call) Run(run func(context1 context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x05_BuddyDelBuddies)) *mockBuddyService_DelBuddies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNAC_0x03_0x05_BuddyDelBuddies
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x03_0x05_BuddyDelBuddies)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockBuddyService_DelBuddies_Call) Return(err error) *mockBuddyService_DelBuddies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyService_DelBuddies_Call) RunAndReturn(run func(context1 context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x05_BuddyDelBuddies) error) *mockBuddyService_DelBuddies_Call {
	_c.Call.Return(run)
	return _c
}

// DelTempBuddies provides a mock function for the type mockBuddyService
func (_mock *mockBuddyService) DelTempBuddies(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x10_BuddyDelTempBuddies) error {
	ret := _mock.Called(ctx, instance, inBody)

	if len(ret) == 0 {
		panic("no return value specified for DelTempBuddies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNAC_0x03_0x10_BuddyDelTempBuddies) error); ok {
		r0 = returnFunc(ctx, instance, inBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyService_DelTempBuddies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelTempBuddies'
type mockBuddyService_DelTempBuddies_Call struct {
	*mock.Call
}

// DelTempBuddies is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inBody wire.SNAC_0x03_0x10_BuddyDelTempBuddies
func (_e *mockBuddyService_Expecter) DelTempBuddies(ctx interface{}, instance interface{}, inBody interface{}) *mockBuddyService_DelTempBuddies_Call {
	return &mockBuddyService_DelTempBuddies_Call{Call: _e.mock.On("DelTempBuddies", ctx, instance, inBody)}
}

func (_c *mockBuddyService_DelTempBuddies_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x10_BuddyDelTempBuddies)) *mockBuddyService_DelTempBuddies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNAC_0x03_0x10_BuddyDelTempBuddies
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x03_0x10_BuddyDelTempBuddies)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockBuddyService_DelTempBuddies_Call) Return(err error) *mockBuddyService_DelTempBuddies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyService_DelTempBuddies_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x10_BuddyDelTempBuddies) error) *mockBuddyService_DelTempBuddies_Call {
	_c.Call.Return(run)
	return _c
}

// RightsQuery provides a mock function for the type mockBuddyService
func (_mock *mockBuddyService) RightsQuery(ctx context.Context, inFrame wire.SNACFrame) wire.SNACMessage {
	ret := _mock.Called(ctx, inFrame)

	if len(ret) == 0 {
		panic("no return value specified for RightsQuery")
	}

	var r0 wire.SNACMessage
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNACFrame) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, inFrame)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	return r0
}

// mockBuddyService_RightsQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RightsQuery'
type mockBuddyService_RightsQuery_Call struct {
	*mock.Call
}

// RightsQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - inFrame wire.SNACFrame
func (_e *mockBuddyService_Expecter) RightsQuery(ctx interface{}, inFrame interface{}) *mockBuddyService_RightsQuery_Call {
	return &mockBuddyService_RightsQuery_Call{Call: _e.mock.On("RightsQuery", ctx, inFrame)}
}

func (_c *mockBuddyService_RightsQuery_Call) Run(run func(ctx context.Context, inFrame wire.SNACFrame)) *mockBuddyService_RightsQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.SNACFrame
		if args[1] != nil {
			arg1 = args[1].(wire.SNACFrame)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockBuddyService_RightsQuery_Call) Return(sNACMessage wire.SNACMessage) *mockBuddyService_RightsQuery_Call {
	_c.Call.Return(sNACMessage)
	return _c
}

func (_c *mockBuddyService_RightsQuery_Call) RunAndReturn(run func(ctx context.Context, inFrame wire.SNACFrame) wire.SNACMessage) *mockBuddyService_RightsQuery_Call {
	_c.Call.Return(run)
	return _c
}
