// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oscar

import (
	"context"

	"github.com/pchchv/go-icq/state"
	"github.com/pchchv/go-icq/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockChatNavService creates a new instance of mockChatNavService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockChatNavService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockChatNavService {
	mock := &mockChatNavService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockChatNavService is an autogenerated mock type for the ChatNavService type
type mockChatNavService struct {
	mock.Mock
}

type mockChatNavService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockChatNavService) EXPECT() *mockChatNavService_Expecter {
	return &mockChatNavService_Expecter{mock: &_m.Mock}
}

// CreateRoom provides a mock function for the type mockChatNavService
func (_mock *mockChatNavService) CreateRoom(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x0E_0x02_ChatRoomInfoUpdate) (wire.SNACMessage, error) {
	ret := _mock.Called(ctx, instance, inFrame, inBody)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x0E_0x02_ChatRoomInfoUpdate) (wire.SNACMessage, error)); ok {
		return returnFunc(ctx, instance, inFrame, inBody)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x0E_0x02_ChatRoomInfoUpdate) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, instance, inFrame, inBody)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x0E_0x02_ChatRoomInfoUpdate) error); ok {
		r1 = returnFunc(ctx, instance, inFrame, inBody)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockChatNavService_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type mockChatNavService_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inFrame wire.SNACFrame
//   - inBody wire.SNAC_0x0E_0x02_ChatRoomInfoUpdate
func (_e *mockChatNavService_Expecter) CreateRoom(ctx interface{}, instance interface{}, inFrame interface{}, inBody interface{}) *mockChatNavService_CreateRoom_Call {
	return &mockChatNavService_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, instance, inFrame, inBody)}
}

func (_c *mockChatNavService_CreateRoom_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x0E_0x02_ChatRoomInfoUpdate)) *mockChatNavService_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNACFrame
		if args[2] != nil {
			arg2 = args[2].(wire.SNACFrame)
		}
		var arg3 wire.SNAC_0x0E_0x02_ChatRoomInfoUpdate
		if args[3] != nil {
			arg3 = args[3].(wire.SNAC_0x0E_0x02_ChatRoomInfoUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockChatNavService_CreateRoom_Call) Return(sNACMessage wire.SNACMessage, err error) *mockChatNavService_CreateRoom_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockChatNavService_CreateRoom_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x0E_0x02_ChatRoomInfoUpdate) (wire.SNACMessage, error)) *mockChatNavService_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeInfo provides a mock function for the type mockChatNavService
func (_mock *mockChatNavService) ExchangeInfo(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0D_0x03_ChatNavRequestExchangeInfo) (wire.SNACMessage, error) {
	ret := _mock.Called(ctx, inFrame, inBody)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeInfo")
	}

	var r0 wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0D_0x03_ChatNavRequestExchangeInfo) (wire.SNACMessage, error)); ok {
		return returnFunc(ctx, inFrame, inBody)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0D_0x03_ChatNavRequestExchangeInfo) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, inFrame, inBody)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0D_0x03_ChatNavRequestExchangeInfo) error); ok {
		r1 = returnFunc(ctx, inFrame, inBody)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockChatNavService_ExchangeInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeInfo'
type mockChatNavService_ExchangeInfo_Call struct {
	*mock.Call
}

// ExchangeInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - inFrame wire.SNACFrame
//   - inBody wire.SNAC_0x0D_0x03_ChatNavRequestExchangeInfo
func (_e *mockChatNavService_Expecter) ExchangeInfo(ctx interface{}, inFrame interface{}, inBody interface{}) *mockChatNavService_ExchangeInfo_Call {
	return &mockChatNavService_ExchangeInfo_Call{Call: _e.mock.On("ExchangeInfo", ctx, inFrame, inBody)}
}

func (_c *mockChatNavService_ExchangeInfo_Call) Run(run func(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0D_0x03_ChatNavRequestExchangeInfo)) *mockChatNavService_ExchangeInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.SNACFrame
		if args[1] != nil {
			arg1 = args[1].(wire.SNACFrame)
		}
		var arg2 wire.SNAC_0x0D_0x03_ChatNavRequestExchangeInfo
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x0D_0x03_ChatNavRequestExchangeInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockChatNavService_ExchangeInfo_Call) Return(sNACMessage wire.SNACMessage, err error) *mockChatNavService_ExchangeInfo_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockChatNavService_ExchangeInfo_Call) RunAndReturn(run func(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0D_0x03_ChatNavRequestExchangeInfo) (wire.SNACMessage, error)) *mockChatNavService_ExchangeInfo_Call {
	_c.Call.Return(run)
	return _c
}

// RequestChatRights provides a mock function for the type mockChatNavService
func (_mock *mockChatNavService) RequestChatRights(ctx context.Context, inFrame wire.SNACFrame) wire.SNACMessage {
	ret := _mock.Called(ctx, inFrame)

	if len(ret) == 0 {
		panic("no return value specified for RequestChatRights")
	}

	var r0 wire.SNACMessage
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNACFrame) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, inFrame)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	return r0
}

// mockChatNavService_RequestChatRights_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestChatRights'
type mockChatNavService_RequestChatRights_Call struct {
	*mock.Call
}

// RequestChatRights is a helper method to define mock.On call
//   - ctx context.Context
//   - inFrame wire.SNACFrame
func (_e *mockChatNavService_Expecter) RequestChatRights(ctx interface{}, inFrame interface{}) *mockChatNavService_RequestChatRights_Call {
	return &mockChatNavService_RequestChatRights_Call{Call: _e.mock.On("RequestChatRights", ctx, inFrame)}
}

func (_c *mockChatNavService_RequestChatRights_Call) Run(run func(ctx context.Context, inFrame wire.SNACFrame)) *mockChatNavService_RequestChatRights_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.SNACFrame
		if args[1] != nil {
			arg1 = args[1].(wire.SNACFrame)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockChatNavService_RequestChatRights_Call) Return(sNACMessage wire.SNACMessage) *mockChatNavService_RequestChatRights_Call {
	_c.Call.Return(sNACMessage)
	return _c
}

func (_c *mockChatNavService_RequestChatRights_Call) RunAndReturn(run func(ctx context.Context, inFrame wire.SNACFrame) wire.SNACMessage) *mockChatNavService_RequestChatRights_Call {
	_c.Call.Return(run)
	return _c
}

// RequestRoomInfo provides a mock function for the type mockChatNavService
func (_mock *mockChatNavService) RequestRoomInfo(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0D_0x04_ChatNavRequestRoomInfo) (wire.SNACMessage, error) {
	ret := _mock.Called(ctx, inFrame, inBody)

	if len(ret) == 0 {
		panic("no return value specified for RequestRoomInfo")
	}

	var r0 wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0D_0x04_ChatNavRequestRoomInfo) (wire.SNACMessage, error)); ok {
		return returnFunc(ctx, inFrame, inBody)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0D_0x04_ChatNavRequestRoomInfo) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, inFrame, inBody)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0D_0x04_ChatNavRequestRoomInfo) error); ok {
		r1 = returnFunc(ctx, inFrame, inBody)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockChatNavService_RequestRoomInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestRoomInfo'
type mockChatNavService_RequestRoomInfo_Call struct {
	*mock.Call
}

// RequestRoomInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - inFrame wire.SNACFrame
//   - inBody wire.SNAC_0x0D_0x04_ChatNavRequestRoomInfo
func (_e *mockChatNavService_Expecter) RequestRoomInfo(ctx interface{}, inFrame interface{}, inBody interface{}) *mockChatNavService_RequestRoomInfo_Call {
	return &mockChatNavService_RequestRoomInfo_Call{Call: _e.mock.On("RequestRoomInfo", ctx, inFrame, inBody)}
}

func (_c *mockChatNavService_RequestRoomInfo_Call) Run(run func(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0D_0x04_ChatNavRequestRoomInfo)) *mockChatNavService_RequestRoomInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.SNACFrame
		if args[1] != nil {
			arg1 = args[1].(wire.SNACFrame)
		}
		var arg2 wire.SNAC_0x0D_0x04_ChatNavRequestRoomInfo
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x0D_0x04_ChatNavRequestRoomInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockChatNavService_RequestRoomInfo_Call) Return(sNACMessage wire.SNACMessage, err error) *mockChatNavService_RequestRoomInfo_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockChatNavService_RequestRoomInfo_Call) RunAndReturn(run func(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0D_0x04_ChatNavRequestRoomInfo) (wire.SNACMessage, error)) *mockChatNavService_RequestRoomInfo_Call {
	_c.Call.Return(run)
	return _c
}
