// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oscar

import (
	"context"

	"github.com/pchchv/go-icq/state"
	"github.com/pchchv/go-icq/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockDepartureNotifier creates a new instance of mockDepartureNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDepartureNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDepartureNotifier {
	mock := &mockDepartureNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockDepartureNotifier is an autogenerated mock type for the DepartureNotifier type
type mockDepartureNotifier struct {
	mock.Mock
}

type mockDepartureNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDepartureNotifier) EXPECT() *mockDepartureNotifier_Expecter {
	return &mockDepartureNotifier_Expecter{mock: &_m.Mock}
}

// BroadcastBuddyArrived provides a mock function for the type mockDepartureNotifier
func (_mock *mockDepartureNotifier) BroadcastBuddyArrived(ctx context.Context, screenName state.IdentScreenName, userInfo wire.TLVUserInfo) error {
	ret := _mock.Called(ctx, screenName, userInfo)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastBuddyArrived")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, wire.TLVUserInfo) error); ok {
		r0 = returnFunc(ctx, screenName, userInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockDepartureNotifier_BroadcastBuddyArrived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastBuddyArrived'
type mockDepartureNotifier_BroadcastBuddyArrived_Call struct {
	*mock.Call
}

// BroadcastBuddyArrived is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - userInfo wire.TLVUserInfo
func (_e *mockDepartureNotifier_Expecter) BroadcastBuddyArrived(ctx interface{}, screenName interface{}, userInfo interface{}) *mockDepartureNotifier_BroadcastBuddyArrived_Call {
	return &mockDepartureNotifier_BroadcastBuddyArrived_Call{Call: _e.mock.On("BroadcastBuddyArrived", ctx, screenName, userInfo)}
}

func (_c *mockDepartureNotifier_BroadcastBuddyArrived_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, userInfo wire.TLVUserInfo)) *mockDepartureNotifier_BroadcastBuddyArrived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 wire.TLVUserInfo
		if args[2] != nil {
			arg2 = args[2].(wire.TLVUserInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDepartureNotifier_BroadcastBuddyArrived_Call) Return(err error) *mockDepartureNotifier_BroadcastBuddyArrived_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockDepartureNotifier_BroadcastBuddyArrived_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, userInfo wire.TLVUserInfo) error) *mockDepartureNotifier_BroadcastBuddyArrived_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastBuddyDeparted provides a mock function for the type mockDepartureNotifier
func (_mock *mockDepartureNotifier) BroadcastBuddyDeparted(ctx context.Context, instance *state.SessionInstance) error {
	ret := _mock.Called(ctx, instance)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastBuddyDeparted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance) error); ok {
		r0 = returnFunc(ctx, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockDepartureNotifier_BroadcastBuddyDeparted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastBuddyDeparted'
type mockDepartureNotifier_BroadcastBuddyDeparted_Call struct {
	*mock.Call
}

// BroadcastBuddyDeparted is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
func (_e *mockDepartureNotifier_Expecter) BroadcastBuddyDeparted(ctx interface{}, instance interface{}) *mockDepartureNotifier_BroadcastBuddyDeparted_Call {
	return &mockDepartureNotifier_BroadcastBuddyDeparted_Call{Call: _e.mock.On("BroadcastBuddyDeparted", ctx, instance)}
}

func (_c *mockDepartureNotifier_BroadcastBuddyDeparted_Call) Run(run func(ctx context.Context, instance *state.SessionInstance)) *mockDepartureNotifier_BroadcastBuddyDeparted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockDepartureNotifier_BroadcastBuddyDeparted_Call) Return(err error) *mockDepartureNotifier_BroadcastBuddyDeparted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockDepartureNotifier_BroadcastBuddyDeparted_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance) error) *mockDepartureNotifier_BroadcastBuddyDeparted_Call {
	_c.Call.Return(run)
	return _c
}
