// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oscar

import (
	"github.com/pchchv/go-icq/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockResponseWriter creates a new instance of mockResponseWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockResponseWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockResponseWriter {
	mock := &mockResponseWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockResponseWriter is an autogenerated mock type for the ResponseWriter type
type mockResponseWriter struct {
	mock.Mock
}

type mockResponseWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockResponseWriter) EXPECT() *mockResponseWriter_Expecter {
	return &mockResponseWriter_Expecter{mock: &_m.Mock}
}

// SendSNAC provides a mock function for the type mockResponseWriter
func (_mock *mockResponseWriter) SendSNAC(frame wire.SNACFrame, body any) error {
	ret := _mock.Called(frame, body)

	if len(ret) == 0 {
		panic("no return value specified for SendSNAC")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(wire.SNACFrame, any) error); ok {
		r0 = returnFunc(frame, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockResponseWriter_SendSNAC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSNAC'
type mockResponseWriter_SendSNAC_Call struct {
	*mock.Call
}

// SendSNAC is a helper method to define mock.On call
//   - frame wire.SNACFrame
//   - body any
func (_e *mockResponseWriter_Expecter) SendSNAC(frame interface{}, body interface{}) *mockResponseWriter_SendSNAC_Call {
	return &mockResponseWriter_SendSNAC_Call{Call: _e.mock.On("SendSNAC", frame, body)}
}

func (_c *mockResponseWriter_SendSNAC_Call) Run(run func(frame wire.SNACFrame, body any)) *mockResponseWriter_SendSNAC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 wire.SNACFrame
		if args[0] != nil {
			arg0 = args[0].(wire.SNACFrame)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockResponseWriter_SendSNAC_Call) Return(err error) *mockResponseWriter_SendSNAC_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockResponseWriter_SendSNAC_Call) RunAndReturn(run func(frame wire.SNACFrame, body any) error) *mockResponseWriter_SendSNAC_Call {
	_c.Call.Return(run)
	return _c
}
