// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oscar

import (
	"context"

	"github.com/pchchv/go-icq/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockUserLookupService creates a new instance of mockUserLookupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUserLookupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUserLookupService {
	mock := &mockUserLookupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockUserLookupService is an autogenerated mock type for the UserLookupService type
type mockUserLookupService struct {
	mock.Mock
}

type mockUserLookupService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUserLookupService) EXPECT() *mockUserLookupService_Expecter {
	return &mockUserLookupService_Expecter{mock: &_m.Mock}
}

// FindByEmail provides a mock function for the type mockUserLookupService
func (_mock *mockUserLookupService) FindByEmail(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0A_0x02_UserLookupFindByEmail) (wire.SNACMessage, error) {
	ret := _mock.Called(ctx, inFrame, inBody)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0A_0x02_UserLookupFindByEmail) (wire.SNACMessage, error)); ok {
		return returnFunc(ctx, inFrame, inBody)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0A_0x02_UserLookupFindByEmail) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, inFrame, inBody)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0A_0x02_UserLookupFindByEmail) error); ok {
		r1 = returnFunc(ctx, inFrame, inBody)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockUserLookupService_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type mockUserLookupService_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - inFrame wire.SNACFrame
//   - inBody wire.SNAC_0x0A_0x02_UserLookupFindByEmail
func (_e *mockUserLookupService_Expecter) FindByEmail(ctx interface{}, inFrame interface{}, inBody interface{}) *mockUserLookupService_FindByEmail_Call {
	return &mockUserLookupService_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, inFrame, inBody)}
}

func (_c *mockUserLookupService_FindByEmail_Call) Run(run func(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0A_0x02_UserLookupFindByEmail)) *mockUserLookupService_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.SNACFrame
		if args[1] != nil {
			arg1 = args[1].(wire.SNACFrame)
		}
		var arg2 wire.SNAC_0x0A_0x02_UserLookupFindByEmail
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x0A_0x02_UserLookupFindByEmail)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockUserLookupService_FindByEmail_Call) Return(sNACMessage wire.SNACMessage, err error) *mockUserLookupService_FindByEmail_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockUserLookupService_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0A_0x02_UserLookupFindByEmail) (wire.SNACMessage, error)) *mockUserLookupService_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}
