// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package foodgroup

import (
	"context"

	"github.com/pchchv/go-icq/state"
	"github.com/pchchv/go-icq/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockBARTItemManager creates a new instance of mockBARTItemManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBARTItemManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBARTItemManager {
	mock := &mockBARTItemManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockBARTItemManager is an autogenerated mock type for the BARTItemManager type
type mockBARTItemManager struct {
	mock.Mock
}

type mockBARTItemManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBARTItemManager) EXPECT() *mockBARTItemManager_Expecter {
	return &mockBARTItemManager_Expecter{mock: &_m.Mock}
}

// BARTItem provides a mock function for the type mockBARTItemManager
func (_mock *mockBARTItemManager) BARTItem(ctx context.Context, hash []byte) ([]byte, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for BARTItem")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockBARTItemManager_BARTItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BARTItem'
type mockBARTItemManager_BARTItem_Call struct {
	*mock.Call
}

// BARTItem is a helper method to define mock.On call
//   - ctx context.Context
//   - hash []byte
func (_e *mockBARTItemManager_Expecter) BARTItem(ctx interface{}, hash interface{}) *mockBARTItemManager_BARTItem_Call {
	return &mockBARTItemManager_BARTItem_Call{Call: _e.mock.On("BARTItem", ctx, hash)}
}

func (_c *mockBARTItemManager_BARTItem_Call) Run(run func(ctx context.Context, hash []byte)) *mockBARTItemManager_BARTItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockBARTItemManager_BARTItem_Call) Return(bytes []byte, err error) *mockBARTItemManager_BARTItem_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockBARTItemManager_BARTItem_Call) RunAndReturn(run func(ctx context.Context, hash []byte) ([]byte, error)) *mockBARTItemManager_BARTItem_Call {
	_c.Call.Return(run)
	return _c
}

// BuddyIconMetadata provides a mock function for the type mockBARTItemManager
func (_mock *mockBARTItemManager) BuddyIconMetadata(ctx context.Context, screenName state.IdentScreenName) (*wire.BARTID, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for BuddyIconMetadata")
	}

	var r0 *wire.BARTID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (*wire.BARTID, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) *wire.BARTID); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wire.BARTID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockBARTItemManager_BuddyIconMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuddyIconMetadata'
type mockBARTItemManager_BuddyIconMetadata_Call struct {
	*mock.Call
}

// BuddyIconMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockBARTItemManager_Expecter) BuddyIconMetadata(ctx interface{}, screenName interface{}) *mockBARTItemManager_BuddyIconMetadata_Call {
	return &mockBARTItemManager_BuddyIconMetadata_Call{Call: _e.mock.On("BuddyIconMetadata", ctx, screenName)}
}

func (_c *mockBARTItemManager_BuddyIconMetadata_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockBARTItemManager_BuddyIconMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockBARTItemManager_BuddyIconMetadata_Call) Return(bARTID *wire.BARTID, err error) *mockBARTItemManager_BuddyIconMetadata_Call {
	_c.Call.Return(bARTID, err)
	return _c
}

func (_c *mockBARTItemManager_BuddyIconMetadata_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (*wire.BARTID, error)) *mockBARTItemManager_BuddyIconMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBARTItem provides a mock function for the type mockBARTItemManager
func (_mock *mockBARTItemManager) DeleteBARTItem(ctx context.Context, hash []byte) error {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBARTItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBARTItemManager_DeleteBARTItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBARTItem'
type mockBARTItemManager_DeleteBARTItem_Call struct {
	*mock.Call
}

// DeleteBARTItem is a helper method to define mock.On call
//   - ctx context.Context
//   - hash []byte
func (_e *mockBARTItemManager_Expecter) DeleteBARTItem(ctx interface{}, hash interface{}) *mockBARTItemManager_DeleteBARTItem_Call {
	return &mockBARTItemManager_DeleteBARTItem_Call{Call: _e.mock.On("DeleteBARTItem", ctx, hash)}
}

func (_c *mockBARTItemManager_DeleteBARTItem_Call) Run(run func(ctx context.Context, hash []byte)) *mockBARTItemManager_DeleteBARTItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockBARTItemManager_DeleteBARTItem_Call) Return(err error) *mockBARTItemManager_DeleteBARTItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBARTItemManager_DeleteBARTItem_Call) RunAndReturn(run func(ctx context.Context, hash []byte) error) *mockBARTItemManager_DeleteBARTItem_Call {
	_c.Call.Return(run)
	return _c
}

// InsertBARTItem provides a mock function for the type mockBARTItemManager
func (_mock *mockBARTItemManager) InsertBARTItem(ctx context.Context, hash []byte, blob []byte, itemType uint16) error {
	ret := _mock.Called(ctx, hash, blob, itemType)

	if len(ret) == 0 {
		panic("no return value specified for InsertBARTItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte, uint16) error); ok {
		r0 = returnFunc(ctx, hash, blob, itemType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBARTItemManager_InsertBARTItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBARTItem'
type mockBARTItemManager_InsertBARTItem_Call struct {
	*mock.Call
}

// InsertBARTItem is a helper method to define mock.On call
//   - ctx context.Context
//   - hash []byte
//   - blob []byte
//   - itemType uint16
func (_e *mockBARTItemManager_Expecter) InsertBARTItem(ctx interface{}, hash interface{}, blob interface{}, itemType interface{}) *mockBARTItemManager_InsertBARTItem_Call {
	return &mockBARTItemManager_InsertBARTItem_Call{Call: _e.mock.On("InsertBARTItem", ctx, hash, blob, itemType)}
}

func (_c *mockBARTItemManager_InsertBARTItem_Call) Run(run func(ctx context.Context, hash []byte, blob []byte, itemType uint16)) *mockBARTItemManager_InsertBARTItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 uint16
		if args[3] != nil {
			arg3 = args[3].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockBARTItemManager_InsertBARTItem_Call) Return(err error) *mockBARTItemManager_InsertBARTItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBARTItemManager_InsertBARTItem_Call) RunAndReturn(run func(ctx context.Context, hash []byte, blob []byte, itemType uint16) error) *mockBARTItemManager_InsertBARTItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListBARTItems provides a mock function for the type mockBARTItemManager
func (_mock *mockBARTItemManager) ListBARTItems(ctx context.Context, itemType uint16) ([]state.BARTItem, error) {
	ret := _mock.Called(ctx, itemType)

	if len(ret) == 0 {
		panic("no return value specified for ListBARTItems")
	}

	var r0 []state.BARTItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16) ([]state.BARTItem, error)); ok {
		return returnFunc(ctx, itemType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16) []state.BARTItem); ok {
		r0 = returnFunc(ctx, itemType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]state.BARTItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint16) error); ok {
		r1 = returnFunc(ctx, itemType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockBARTItemManager_ListBARTItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBARTItems'
type mockBARTItemManager_ListBARTItems_Call struct {
	*mock.Call
}

// ListBARTItems is a helper method to define mock.On call
//   - ctx context.Context
//   - itemType uint16
func (_e *mockBARTItemManager_Expecter) ListBARTItems(ctx interface{}, itemType interface{}) *mockBARTItemManager_ListBARTItems_Call {
	return &mockBARTItemManager_ListBARTItems_Call{Call: _e.mock.On("ListBARTItems", ctx, itemType)}
}

func (_c *mockBARTItemManager_ListBARTItems_Call) Run(run func(ctx context.Context, itemType uint16)) *mockBARTItemManager_ListBARTItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockBARTItemManager_ListBARTItems_Call) Return(bARTItems []state.BARTItem, err error) *mockBARTItemManager_ListBARTItems_Call {
	_c.Call.Return(bARTItems, err)
	return _c
}

func (_c *mockBARTItemManager_ListBARTItems_Call) RunAndReturn(run func(ctx context.Context, itemType uint16) ([]state.BARTItem, error)) *mockBARTItemManager_ListBARTItems_Call {
	_c.Call.Return(run)
	return _c
}
