// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package foodgroup

import (
	"context"
	"net/mail"

	"github.com/pchchv/go-icq/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockAccountManager creates a new instance of mockAccountManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAccountManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAccountManager {
	mock := &mockAccountManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAccountManager is an autogenerated mock type for the AccountManager type
type mockAccountManager struct {
	mock.Mock
}

type mockAccountManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAccountManager) EXPECT() *mockAccountManager_Expecter {
	return &mockAccountManager_Expecter{mock: &_m.Mock}
}

// ConfirmStatus provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) ConfirmStatus(ctx context.Context, screenName state.IdentScreenName) (bool, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmStatus")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (bool, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) bool); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAccountManager_ConfirmStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmStatus'
type mockAccountManager_ConfirmStatus_Call struct {
	*mock.Call
}

// ConfirmStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockAccountManager_Expecter) ConfirmStatus(ctx interface{}, screenName interface{}) *mockAccountManager_ConfirmStatus_Call {
	return &mockAccountManager_ConfirmStatus_Call{Call: _e.mock.On("ConfirmStatus", ctx, screenName)}
}

func (_c *mockAccountManager_ConfirmStatus_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockAccountManager_ConfirmStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAccountManager_ConfirmStatus_Call) Return(b bool, err error) *mockAccountManager_ConfirmStatus_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockAccountManager_ConfirmStatus_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (bool, error)) *mockAccountManager_ConfirmStatus_Call {
	_c.Call.Return(run)
	return _c
}

// EmailAddress provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) EmailAddress(ctx context.Context, screenName state.IdentScreenName) (*mail.Address, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for EmailAddress")
	}

	var r0 *mail.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (*mail.Address, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) *mail.Address); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mail.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAccountManager_EmailAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmailAddress'
type mockAccountManager_EmailAddress_Call struct {
	*mock.Call
}

// EmailAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockAccountManager_Expecter) EmailAddress(ctx interface{}, screenName interface{}) *mockAccountManager_EmailAddress_Call {
	return &mockAccountManager_EmailAddress_Call{Call: _e.mock.On("EmailAddress", ctx, screenName)}
}

func (_c *mockAccountManager_EmailAddress_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockAccountManager_EmailAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAccountManager_EmailAddress_Call) Return(address *mail.Address, err error) *mockAccountManager_EmailAddress_Call {
	_c.Call.Return(address, err)
	return _c
}

func (_c *mockAccountManager_EmailAddress_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (*mail.Address, error)) *mockAccountManager_EmailAddress_Call {
	_c.Call.Return(run)
	return _c
}

// RegStatus provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) RegStatus(ctx context.Context, screenName state.IdentScreenName) (uint16, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for RegStatus")
	}

	var r0 uint16
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (uint16, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) uint16); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		r0 = ret.Get(0).(uint16)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAccountManager_RegStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegStatus'
type mockAccountManager_RegStatus_Call struct {
	*mock.Call
}

// RegStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockAccountManager_Expecter) RegStatus(ctx interface{}, screenName interface{}) *mockAccountManager_RegStatus_Call {
	return &mockAccountManager_RegStatus_Call{Call: _e.mock.On("RegStatus", ctx, screenName)}
}

func (_c *mockAccountManager_RegStatus_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockAccountManager_RegStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAccountManager_RegStatus_Call) Return(v uint16, err error) *mockAccountManager_RegStatus_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *mockAccountManager_RegStatus_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (uint16, error)) *mockAccountManager_RegStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserPassword provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) SetUserPassword(ctx context.Context, screenName state.IdentScreenName, newPassword string) error {
	ret := _mock.Called(ctx, screenName, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for SetUserPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, string) error); ok {
		r0 = returnFunc(ctx, screenName, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAccountManager_SetUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserPassword'
type mockAccountManager_SetUserPassword_Call struct {
	*mock.Call
}

// SetUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - newPassword string
func (_e *mockAccountManager_Expecter) SetUserPassword(ctx interface{}, screenName interface{}, newPassword interface{}) *mockAccountManager_SetUserPassword_Call {
	return &mockAccountManager_SetUserPassword_Call{Call: _e.mock.On("SetUserPassword", ctx, screenName, newPassword)}
}

func (_c *mockAccountManager_SetUserPassword_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, newPassword string)) *mockAccountManager_SetUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAccountManager_SetUserPassword_Call) Return(err error) *mockAccountManager_SetUserPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAccountManager_SetUserPassword_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, newPassword string) error) *mockAccountManager_SetUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConfirmStatus provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) UpdateConfirmStatus(ctx context.Context, screenName state.IdentScreenName, confirmStatus bool) error {
	ret := _mock.Called(ctx, screenName, confirmStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConfirmStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, bool) error); ok {
		r0 = returnFunc(ctx, screenName, confirmStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAccountManager_UpdateConfirmStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConfirmStatus'
type mockAccountManager_UpdateConfirmStatus_Call struct {
	*mock.Call
}

// UpdateConfirmStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - confirmStatus bool
func (_e *mockAccountManager_Expecter) UpdateConfirmStatus(ctx interface{}, screenName interface{}, confirmStatus interface{}) *mockAccountManager_UpdateConfirmStatus_Call {
	return &mockAccountManager_UpdateConfirmStatus_Call{Call: _e.mock.On("UpdateConfirmStatus", ctx, screenName, confirmStatus)}
}

func (_c *mockAccountManager_UpdateConfirmStatus_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, confirmStatus bool)) *mockAccountManager_UpdateConfirmStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAccountManager_UpdateConfirmStatus_Call) Return(err error) *mockAccountManager_UpdateConfirmStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAccountManager_UpdateConfirmStatus_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, confirmStatus bool) error) *mockAccountManager_UpdateConfirmStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDisplayScreenName provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) UpdateDisplayScreenName(ctx context.Context, displayScreenName state.DisplayScreenName) error {
	ret := _mock.Called(ctx, displayScreenName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDisplayScreenName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.DisplayScreenName) error); ok {
		r0 = returnFunc(ctx, displayScreenName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAccountManager_UpdateDisplayScreenName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDisplayScreenName'
type mockAccountManager_UpdateDisplayScreenName_Call struct {
	*mock.Call
}

// UpdateDisplayScreenName is a helper method to define mock.On call
//   - ctx context.Context
//   - displayScreenName state.DisplayScreenName
func (_e *mockAccountManager_Expecter) UpdateDisplayScreenName(ctx interface{}, displayScreenName interface{}) *mockAccountManager_UpdateDisplayScreenName_Call {
	return &mockAccountManager_UpdateDisplayScreenName_Call{Call: _e.mock.On("UpdateDisplayScreenName", ctx, displayScreenName)}
}

func (_c *mockAccountManager_UpdateDisplayScreenName_Call) Run(run func(ctx context.Context, displayScreenName state.DisplayScreenName)) *mockAccountManager_UpdateDisplayScreenName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.DisplayScreenName
		if args[1] != nil {
			arg1 = args[1].(state.DisplayScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAccountManager_UpdateDisplayScreenName_Call) Return(err error) *mockAccountManager_UpdateDisplayScreenName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAccountManager_UpdateDisplayScreenName_Call) RunAndReturn(run func(ctx context.Context, displayScreenName state.DisplayScreenName) error) *mockAccountManager_UpdateDisplayScreenName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEmailAddress provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) UpdateEmailAddress(ctx context.Context, screenName state.IdentScreenName, emailAddress *mail.Address) error {
	ret := _mock.Called(ctx, screenName, emailAddress)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmailAddress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, *mail.Address) error); ok {
		r0 = returnFunc(ctx, screenName, emailAddress)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAccountManager_UpdateEmailAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEmailAddress'
type mockAccountManager_UpdateEmailAddress_Call struct {
	*mock.Call
}

// UpdateEmailAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - emailAddress *mail.Address
func (_e *mockAccountManager_Expecter) UpdateEmailAddress(ctx interface{}, screenName interface{}, emailAddress interface{}) *mockAccountManager_UpdateEmailAddress_Call {
	return &mockAccountManager_UpdateEmailAddress_Call{Call: _e.mock.On("UpdateEmailAddress", ctx, screenName, emailAddress)}
}

func (_c *mockAccountManager_UpdateEmailAddress_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, emailAddress *mail.Address)) *mockAccountManager_UpdateEmailAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 *mail.Address
		if args[2] != nil {
			arg2 = args[2].(*mail.Address)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAccountManager_UpdateEmailAddress_Call) Return(err error) *mockAccountManager_UpdateEmailAddress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAccountManager_UpdateEmailAddress_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, emailAddress *mail.Address) error) *mockAccountManager_UpdateEmailAddress_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRegStatus provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) UpdateRegStatus(ctx context.Context, screenName state.IdentScreenName, regStatus uint16) error {
	ret := _mock.Called(ctx, screenName, regStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRegStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, uint16) error); ok {
		r0 = returnFunc(ctx, screenName, regStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAccountManager_UpdateRegStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRegStatus'
type mockAccountManager_UpdateRegStatus_Call struct {
	*mock.Call
}

// UpdateRegStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - regStatus uint16
func (_e *mockAccountManager_Expecter) UpdateRegStatus(ctx interface{}, screenName interface{}, regStatus interface{}) *mockAccountManager_UpdateRegStatus_Call {
	return &mockAccountManager_UpdateRegStatus_Call{Call: _e.mock.On("UpdateRegStatus", ctx, screenName, regStatus)}
}

func (_c *mockAccountManager_UpdateRegStatus_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, regStatus uint16)) *mockAccountManager_UpdateRegStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAccountManager_UpdateRegStatus_Call) Return(err error) *mockAccountManager_UpdateRegStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAccountManager_UpdateRegStatus_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, regStatus uint16) error) *mockAccountManager_UpdateRegStatus_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) User(ctx context.Context, screenName state.IdentScreenName) (*state.User, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 *state.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (*state.User, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) *state.User); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAccountManager_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type mockAccountManager_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockAccountManager_Expecter) User(ctx interface{}, screenName interface{}) *mockAccountManager_User_Call {
	return &mockAccountManager_User_Call{Call: _e.mock.On("User", ctx, screenName)}
}

func (_c *mockAccountManager_User_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockAccountManager_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAccountManager_User_Call) Return(user *state.User, err error) *mockAccountManager_User_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockAccountManager_User_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (*state.User, error)) *mockAccountManager_User_Call {
	_c.Call.Return(run)
	return _c
}
