// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package foodgroup

import (
	"context"

	"github.com/pchchv/go-icq/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockOfflineMessageManager creates a new instance of mockOfflineMessageManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOfflineMessageManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOfflineMessageManager {
	mock := &mockOfflineMessageManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockOfflineMessageManager is an autogenerated mock type for the OfflineMessageManager type
type mockOfflineMessageManager struct {
	mock.Mock
}

type mockOfflineMessageManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOfflineMessageManager) EXPECT() *mockOfflineMessageManager_Expecter {
	return &mockOfflineMessageManager_Expecter{mock: &_m.Mock}
}

// DeleteMessages provides a mock function for the type mockOfflineMessageManager
func (_mock *mockOfflineMessageManager) DeleteMessages(ctx context.Context, recip state.IdentScreenName) error {
	ret := _mock.Called(ctx, recip)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, recip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockOfflineMessageManager_DeleteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessages'
type mockOfflineMessageManager_DeleteMessages_Call struct {
	*mock.Call
}

// DeleteMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - recip state.IdentScreenName
func (_e *mockOfflineMessageManager_Expecter) DeleteMessages(ctx interface{}, recip interface{}) *mockOfflineMessageManager_DeleteMessages_Call {
	return &mockOfflineMessageManager_DeleteMessages_Call{Call: _e.mock.On("DeleteMessages", ctx, recip)}
}

func (_c *mockOfflineMessageManager_DeleteMessages_Call) Run(run func(ctx context.Context, recip state.IdentScreenName)) *mockOfflineMessageManager_DeleteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockOfflineMessageManager_DeleteMessages_Call) Return(err error) *mockOfflineMessageManager_DeleteMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockOfflineMessageManager_DeleteMessages_Call) RunAndReturn(run func(ctx context.Context, recip state.IdentScreenName) error) *mockOfflineMessageManager_DeleteMessages_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveMessages provides a mock function for the type mockOfflineMessageManager
func (_mock *mockOfflineMessageManager) RetrieveMessages(ctx context.Context, recip state.IdentScreenName) ([]state.OfflineMessage, error) {
	ret := _mock.Called(ctx, recip)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveMessages")
	}

	var r0 []state.OfflineMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) ([]state.OfflineMessage, error)); ok {
		return returnFunc(ctx, recip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) []state.OfflineMessage); ok {
		r0 = returnFunc(ctx, recip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]state.OfflineMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, recip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockOfflineMessageManager_RetrieveMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveMessages'
type mockOfflineMessageManager_RetrieveMessages_Call struct {
	*mock.Call
}

// RetrieveMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - recip state.IdentScreenName
func (_e *mockOfflineMessageManager_Expecter) RetrieveMessages(ctx interface{}, recip interface{}) *mockOfflineMessageManager_RetrieveMessages_Call {
	return &mockOfflineMessageManager_RetrieveMessages_Call{Call: _e.mock.On("RetrieveMessages", ctx, recip)}
}

func (_c *mockOfflineMessageManager_RetrieveMessages_Call) Run(run func(ctx context.Context, recip state.IdentScreenName)) *mockOfflineMessageManager_RetrieveMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockOfflineMessageManager_RetrieveMessages_Call) Return(offlineMessages []state.OfflineMessage, err error) *mockOfflineMessageManager_RetrieveMessages_Call {
	_c.Call.Return(offlineMessages, err)
	return _c
}

func (_c *mockOfflineMessageManager_RetrieveMessages_Call) RunAndReturn(run func(ctx context.Context, recip state.IdentScreenName) ([]state.OfflineMessage, error)) *mockOfflineMessageManager_RetrieveMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMessage provides a mock function for the type mockOfflineMessageManager
func (_mock *mockOfflineMessageManager) SaveMessage(ctx context.Context, offlineMessage state.OfflineMessage) (int, error) {
	ret := _mock.Called(ctx, offlineMessage)

	if len(ret) == 0 {
		panic("no return value specified for SaveMessage")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.OfflineMessage) (int, error)); ok {
		return returnFunc(ctx, offlineMessage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.OfflineMessage) int); ok {
		r0 = returnFunc(ctx, offlineMessage)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.OfflineMessage) error); ok {
		r1 = returnFunc(ctx, offlineMessage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockOfflineMessageManager_SaveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMessage'
type mockOfflineMessageManager_SaveMessage_Call struct {
	*mock.Call
}

// SaveMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - offlineMessage state.OfflineMessage
func (_e *mockOfflineMessageManager_Expecter) SaveMessage(ctx interface{}, offlineMessage interface{}) *mockOfflineMessageManager_SaveMessage_Call {
	return &mockOfflineMessageManager_SaveMessage_Call{Call: _e.mock.On("SaveMessage", ctx, offlineMessage)}
}

func (_c *mockOfflineMessageManager_SaveMessage_Call) Run(run func(ctx context.Context, offlineMessage state.OfflineMessage)) *mockOfflineMessageManager_SaveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.OfflineMessage
		if args[1] != nil {
			arg1 = args[1].(state.OfflineMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockOfflineMessageManager_SaveMessage_Call) Return(n int, err error) *mockOfflineMessageManager_SaveMessage_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockOfflineMessageManager_SaveMessage_Call) RunAndReturn(run func(ctx context.Context, offlineMessage state.OfflineMessage) (int, error)) *mockOfflineMessageManager_SaveMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SetOfflineMsgCount provides a mock function for the type mockOfflineMessageManager
func (_mock *mockOfflineMessageManager) SetOfflineMsgCount(ctx context.Context, screenName state.IdentScreenName, count int) error {
	ret := _mock.Called(ctx, screenName, count)

	if len(ret) == 0 {
		panic("no return value specified for SetOfflineMsgCount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, int) error); ok {
		r0 = returnFunc(ctx, screenName, count)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockOfflineMessageManager_SetOfflineMsgCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOfflineMsgCount'
type mockOfflineMessageManager_SetOfflineMsgCount_Call struct {
	*mock.Call
}

// SetOfflineMsgCount is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - count int
func (_e *mockOfflineMessageManager_Expecter) SetOfflineMsgCount(ctx interface{}, screenName interface{}, count interface{}) *mockOfflineMessageManager_SetOfflineMsgCount_Call {
	return &mockOfflineMessageManager_SetOfflineMsgCount_Call{Call: _e.mock.On("SetOfflineMsgCount", ctx, screenName, count)}
}

func (_c *mockOfflineMessageManager_SetOfflineMsgCount_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, count int)) *mockOfflineMessageManager_SetOfflineMsgCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockOfflineMessageManager_SetOfflineMsgCount_Call) Return(err error) *mockOfflineMessageManager_SetOfflineMsgCount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockOfflineMessageManager_SetOfflineMsgCount_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, count int) error) *mockOfflineMessageManager_SetOfflineMsgCount_Call {
	_c.Call.Return(run)
	return _c
}
