// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package foodgroup

import (
	"context"

	"github.com/pchchv/go-icq/state"
	"github.com/pchchv/go-icq/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockChatMessageRelayer creates a new instance of mockChatMessageRelayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockChatMessageRelayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockChatMessageRelayer {
	mock := &mockChatMessageRelayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockChatMessageRelayer is an autogenerated mock type for the ChatMessageRelayer type
type mockChatMessageRelayer struct {
	mock.Mock
}

type mockChatMessageRelayer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockChatMessageRelayer) EXPECT() *mockChatMessageRelayer_Expecter {
	return &mockChatMessageRelayer_Expecter{mock: &_m.Mock}
}

// AllSessions provides a mock function for the type mockChatMessageRelayer
func (_mock *mockChatMessageRelayer) AllSessions(chatCookie string) []*state.Session {
	ret := _mock.Called(chatCookie)

	if len(ret) == 0 {
		panic("no return value specified for AllSessions")
	}

	var r0 []*state.Session
	if returnFunc, ok := ret.Get(0).(func(string) []*state.Session); ok {
		r0 = returnFunc(chatCookie)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*state.Session)
		}
	}
	return r0
}

// mockChatMessageRelayer_AllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllSessions'
type mockChatMessageRelayer_AllSessions_Call struct {
	*mock.Call
}

// AllSessions is a helper method to define mock.On call
//   - chatCookie string
func (_e *mockChatMessageRelayer_Expecter) AllSessions(chatCookie interface{}) *mockChatMessageRelayer_AllSessions_Call {
	return &mockChatMessageRelayer_AllSessions_Call{Call: _e.mock.On("AllSessions", chatCookie)}
}

func (_c *mockChatMessageRelayer_AllSessions_Call) Run(run func(chatCookie string)) *mockChatMessageRelayer_AllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockChatMessageRelayer_AllSessions_Call) Return(sessions []*state.Session) *mockChatMessageRelayer_AllSessions_Call {
	_c.Call.Return(sessions)
	return _c
}

func (_c *mockChatMessageRelayer_AllSessions_Call) RunAndReturn(run func(chatCookie string) []*state.Session) *mockChatMessageRelayer_AllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RelayToAllExcept provides a mock function for the type mockChatMessageRelayer
func (_mock *mockChatMessageRelayer) RelayToAllExcept(ctx context.Context, chatCookie string, except state.IdentScreenName, msg wire.SNACMessage) {
	_mock.Called(ctx, chatCookie, except, msg)
	return
}

// mockChatMessageRelayer_RelayToAllExcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RelayToAllExcept'
type mockChatMessageRelayer_RelayToAllExcept_Call struct {
	*mock.Call
}

// RelayToAllExcept is a helper method to define mock.On call
//   - ctx context.Context
//   - chatCookie string
//   - except state.IdentScreenName
//   - msg wire.SNACMessage
func (_e *mockChatMessageRelayer_Expecter) RelayToAllExcept(ctx interface{}, chatCookie interface{}, except interface{}, msg interface{}) *mockChatMessageRelayer_RelayToAllExcept_Call {
	return &mockChatMessageRelayer_RelayToAllExcept_Call{Call: _e.mock.On("RelayToAllExcept", ctx, chatCookie, except, msg)}
}

func (_c *mockChatMessageRelayer_RelayToAllExcept_Call) Run(run func(ctx context.Context, chatCookie string, except state.IdentScreenName, msg wire.SNACMessage)) *mockChatMessageRelayer_RelayToAllExcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].(state.IdentScreenName)
		}
		var arg3 wire.SNACMessage
		if args[3] != nil {
			arg3 = args[3].(wire.SNACMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockChatMessageRelayer_RelayToAllExcept_Call) Return() *mockChatMessageRelayer_RelayToAllExcept_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockChatMessageRelayer_RelayToAllExcept_Call) RunAndReturn(run func(ctx context.Context, chatCookie string, except state.IdentScreenName, msg wire.SNACMessage)) *mockChatMessageRelayer_RelayToAllExcept_Call {
	_c.Run(run)
	return _c
}

// RelayToScreenName provides a mock function for the type mockChatMessageRelayer
func (_mock *mockChatMessageRelayer) RelayToScreenName(ctx context.Context, chatCookie string, recipient state.IdentScreenName, msg wire.SNACMessage) {
	_mock.Called(ctx, chatCookie, recipient, msg)
	return
}

// mockChatMessageRelayer_RelayToScreenName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RelayToScreenName'
type mockChatMessageRelayer_RelayToScreenName_Call struct {
	*mock.Call
}

// RelayToScreenName is a helper method to define mock.On call
//   - ctx context.Context
//   - chatCookie string
//   - recipient state.IdentScreenName
//   - msg wire.SNACMessage
func (_e *mockChatMessageRelayer_Expecter) RelayToScreenName(ctx interface{}, chatCookie interface{}, recipient interface{}, msg interface{}) *mockChatMessageRelayer_RelayToScreenName_Call {
	return &mockChatMessageRelayer_RelayToScreenName_Call{Call: _e.mock.On("RelayToScreenName", ctx, chatCookie, recipient, msg)}
}

func (_c *mockChatMessageRelayer_RelayToScreenName_Call) Run(run func(ctx context.Context, chatCookie string, recipient state.IdentScreenName, msg wire.SNACMessage)) *mockChatMessageRelayer_RelayToScreenName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].(state.IdentScreenName)
		}
		var arg3 wire.SNACMessage
		if args[3] != nil {
			arg3 = args[3].(wire.SNACMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockChatMessageRelayer_RelayToScreenName_Call) Return() *mockChatMessageRelayer_RelayToScreenName_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockChatMessageRelayer_RelayToScreenName_Call) RunAndReturn(run func(ctx context.Context, chatCookie string, recipient state.IdentScreenName, msg wire.SNACMessage)) *mockChatMessageRelayer_RelayToScreenName_Call {
	_c.Run(run)
	return _c
}
