// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package foodgroup

import (
	"context"

	"github.com/pchchv/go-icq/state"
	"github.com/pchchv/go-icq/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockProfileManager creates a new instance of mockProfileManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockProfileManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockProfileManager {
	mock := &mockProfileManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockProfileManager is an autogenerated mock type for the ProfileManager type
type mockProfileManager struct {
	mock.Mock
}

type mockProfileManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockProfileManager) EXPECT() *mockProfileManager_Expecter {
	return &mockProfileManager_Expecter{mock: &_m.Mock}
}

// FindByAIMEmail provides a mock function for the type mockProfileManager
func (_mock *mockProfileManager) FindByAIMEmail(ctx context.Context, email string) (state.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByAIMEmail")
	}

	var r0 state.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (state.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) state.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(state.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockProfileManager_FindByAIMEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAIMEmail'
type mockProfileManager_FindByAIMEmail_Call struct {
	*mock.Call
}

// FindByAIMEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *mockProfileManager_Expecter) FindByAIMEmail(ctx interface{}, email interface{}) *mockProfileManager_FindByAIMEmail_Call {
	return &mockProfileManager_FindByAIMEmail_Call{Call: _e.mock.On("FindByAIMEmail", ctx, email)}
}

func (_c *mockProfileManager_FindByAIMEmail_Call) Run(run func(ctx context.Context, email string)) *mockProfileManager_FindByAIMEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockProfileManager_FindByAIMEmail_Call) Return(user state.User, err error) *mockProfileManager_FindByAIMEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockProfileManager_FindByAIMEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (state.User, error)) *mockProfileManager_FindByAIMEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAIMKeyword provides a mock function for the type mockProfileManager
func (_mock *mockProfileManager) FindByAIMKeyword(ctx context.Context, keyword string) ([]state.User, error) {
	ret := _mock.Called(ctx, keyword)

	if len(ret) == 0 {
		panic("no return value specified for FindByAIMKeyword")
	}

	var r0 []state.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]state.User, error)); ok {
		return returnFunc(ctx, keyword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []state.User); ok {
		r0 = returnFunc(ctx, keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]state.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keyword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockProfileManager_FindByAIMKeyword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAIMKeyword'
type mockProfileManager_FindByAIMKeyword_Call struct {
	*mock.Call
}

// FindByAIMKeyword is a helper method to define mock.On call
//   - ctx context.Context
//   - keyword string
func (_e *mockProfileManager_Expecter) FindByAIMKeyword(ctx interface{}, keyword interface{}) *mockProfileManager_FindByAIMKeyword_Call {
	return &mockProfileManager_FindByAIMKeyword_Call{Call: _e.mock.On("FindByAIMKeyword", ctx, keyword)}
}

func (_c *mockProfileManager_FindByAIMKeyword_Call) Run(run func(ctx context.Context, keyword string)) *mockProfileManager_FindByAIMKeyword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockProfileManager_FindByAIMKeyword_Call) Return(users []state.User, err error) *mockProfileManager_FindByAIMKeyword_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *mockProfileManager_FindByAIMKeyword_Call) RunAndReturn(run func(ctx context.Context, keyword string) ([]state.User, error)) *mockProfileManager_FindByAIMKeyword_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAIMNameAndAddr provides a mock function for the type mockProfileManager
func (_mock *mockProfileManager) FindByAIMNameAndAddr(ctx context.Context, info state.AIMNameAndAddr) ([]state.User, error) {
	ret := _mock.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for FindByAIMNameAndAddr")
	}

	var r0 []state.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.AIMNameAndAddr) ([]state.User, error)); ok {
		return returnFunc(ctx, info)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.AIMNameAndAddr) []state.User); ok {
		r0 = returnFunc(ctx, info)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]state.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.AIMNameAndAddr) error); ok {
		r1 = returnFunc(ctx, info)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockProfileManager_FindByAIMNameAndAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAIMNameAndAddr'
type mockProfileManager_FindByAIMNameAndAddr_Call struct {
	*mock.Call
}

// FindByAIMNameAndAddr is a helper method to define mock.On call
//   - ctx context.Context
//   - info state.AIMNameAndAddr
func (_e *mockProfileManager_Expecter) FindByAIMNameAndAddr(ctx interface{}, info interface{}) *mockProfileManager_FindByAIMNameAndAddr_Call {
	return &mockProfileManager_FindByAIMNameAndAddr_Call{Call: _e.mock.On("FindByAIMNameAndAddr", ctx, info)}
}

func (_c *mockProfileManager_FindByAIMNameAndAddr_Call) Run(run func(ctx context.Context, info state.AIMNameAndAddr)) *mockProfileManager_FindByAIMNameAndAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.AIMNameAndAddr
		if args[1] != nil {
			arg1 = args[1].(state.AIMNameAndAddr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockProfileManager_FindByAIMNameAndAddr_Call) Return(users []state.User, err error) *mockProfileManager_FindByAIMNameAndAddr_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *mockProfileManager_FindByAIMNameAndAddr_Call) RunAndReturn(run func(ctx context.Context, info state.AIMNameAndAddr) ([]state.User, error)) *mockProfileManager_FindByAIMNameAndAddr_Call {
	_c.Call.Return(run)
	return _c
}

// InterestList provides a mock function for the type mockProfileManager
func (_mock *mockProfileManager) InterestList(ctx context.Context) ([]wire.ODirKeywordListItem, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InterestList")
	}

	var r0 []wire.ODirKeywordListItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]wire.ODirKeywordListItem, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []wire.ODirKeywordListItem); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wire.ODirKeywordListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockProfileManager_InterestList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InterestList'
type mockProfileManager_InterestList_Call struct {
	*mock.Call
}

// InterestList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockProfileManager_Expecter) InterestList(ctx interface{}) *mockProfileManager_InterestList_Call {
	return &mockProfileManager_InterestList_Call{Call: _e.mock.On("InterestList", ctx)}
}

func (_c *mockProfileManager_InterestList_Call) Run(run func(ctx context.Context)) *mockProfileManager_InterestList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockProfileManager_InterestList_Call) Return(oDirKeywordListItems []wire.ODirKeywordListItem, err error) *mockProfileManager_InterestList_Call {
	_c.Call.Return(oDirKeywordListItems, err)
	return _c
}

func (_c *mockProfileManager_InterestList_Call) RunAndReturn(run func(ctx context.Context) ([]wire.ODirKeywordListItem, error)) *mockProfileManager_InterestList_Call {
	_c.Call.Return(run)
	return _c
}

// Profile provides a mock function for the type mockProfileManager
func (_mock *mockProfileManager) Profile(ctx context.Context, screenName state.IdentScreenName) (state.UserProfile, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for Profile")
	}

	var r0 state.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (state.UserProfile, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) state.UserProfile); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		r0 = ret.Get(0).(state.UserProfile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockProfileManager_Profile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Profile'
type mockProfileManager_Profile_Call struct {
	*mock.Call
}

// Profile is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockProfileManager_Expecter) Profile(ctx interface{}, screenName interface{}) *mockProfileManager_Profile_Call {
	return &mockProfileManager_Profile_Call{Call: _e.mock.On("Profile", ctx, screenName)}
}

func (_c *mockProfileManager_Profile_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockProfileManager_Profile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockProfileManager_Profile_Call) Return(userProfile state.UserProfile, err error) *mockProfileManager_Profile_Call {
	_c.Call.Return(userProfile, err)
	return _c
}

func (_c *mockProfileManager_Profile_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (state.UserProfile, error)) *mockProfileManager_Profile_Call {
	_c.Call.Return(run)
	return _c
}

// SetDirectoryInfo provides a mock function for the type mockProfileManager
func (_mock *mockProfileManager) SetDirectoryInfo(ctx context.Context, screenName state.IdentScreenName, info state.AIMNameAndAddr) error {
	ret := _mock.Called(ctx, screenName, info)

	if len(ret) == 0 {
		panic("no return value specified for SetDirectoryInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.AIMNameAndAddr) error); ok {
		r0 = returnFunc(ctx, screenName, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockProfileManager_SetDirectoryInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDirectoryInfo'
type mockProfileManager_SetDirectoryInfo_Call struct {
	*mock.Call
}

// SetDirectoryInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - info state.AIMNameAndAddr
func (_e *mockProfileManager_Expecter) SetDirectoryInfo(ctx interface{}, screenName interface{}, info interface{}) *mockProfileManager_SetDirectoryInfo_Call {
	return &mockProfileManager_SetDirectoryInfo_Call{Call: _e.mock.On("SetDirectoryInfo", ctx, screenName, info)}
}

func (_c *mockProfileManager_SetDirectoryInfo_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, info state.AIMNameAndAddr)) *mockProfileManager_SetDirectoryInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 state.AIMNameAndAddr
		if args[2] != nil {
			arg2 = args[2].(state.AIMNameAndAddr)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockProfileManager_SetDirectoryInfo_Call) Return(err error) *mockProfileManager_SetDirectoryInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockProfileManager_SetDirectoryInfo_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, info state.AIMNameAndAddr) error) *mockProfileManager_SetDirectoryInfo_Call {
	_c.Call.Return(run)
	return _c
}

// SetKeywords provides a mock function for the type mockProfileManager
func (_mock *mockProfileManager) SetKeywords(ctx context.Context, screenName state.IdentScreenName, keywords [5]string) error {
	ret := _mock.Called(ctx, screenName, keywords)

	if len(ret) == 0 {
		panic("no return value specified for SetKeywords")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, [5]string) error); ok {
		r0 = returnFunc(ctx, screenName, keywords)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockProfileManager_SetKeywords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKeywords'
type mockProfileManager_SetKeywords_Call struct {
	*mock.Call
}

// SetKeywords is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - keywords [5]string
func (_e *mockProfileManager_Expecter) SetKeywords(ctx interface{}, screenName interface{}, keywords interface{}) *mockProfileManager_SetKeywords_Call {
	return &mockProfileManager_SetKeywords_Call{Call: _e.mock.On("SetKeywords", ctx, screenName, keywords)}
}

func (_c *mockProfileManager_SetKeywords_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, keywords [5]string)) *mockProfileManager_SetKeywords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 [5]string
		if args[2] != nil {
			arg2 = args[2].([5]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockProfileManager_SetKeywords_Call) Return(err error) *mockProfileManager_SetKeywords_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockProfileManager_SetKeywords_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, keywords [5]string) error) *mockProfileManager_SetKeywords_Call {
	_c.Call.Return(run)
	return _c
}

// SetProfile provides a mock function for the type mockProfileManager
func (_mock *mockProfileManager) SetProfile(ctx context.Context, screenName state.IdentScreenName, profile state.UserProfile) error {
	ret := _mock.Called(ctx, screenName, profile)

	if len(ret) == 0 {
		panic("no return value specified for SetProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.UserProfile) error); ok {
		r0 = returnFunc(ctx, screenName, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockProfileManager_SetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProfile'
type mockProfileManager_SetProfile_Call struct {
	*mock.Call
}

// SetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - profile state.UserProfile
func (_e *mockProfileManager_Expecter) SetProfile(ctx interface{}, screenName interface{}, profile interface{}) *mockProfileManager_SetProfile_Call {
	return &mockProfileManager_SetProfile_Call{Call: _e.mock.On("SetProfile", ctx, screenName, profile)}
}

func (_c *mockProfileManager_SetProfile_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, profile state.UserProfile)) *mockProfileManager_SetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 state.UserProfile
		if args[2] != nil {
			arg2 = args[2].(state.UserProfile)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockProfileManager_SetProfile_Call) Return(err error) *mockProfileManager_SetProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockProfileManager_SetProfile_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, profile state.UserProfile) error) *mockProfileManager_SetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function for the type mockProfileManager
func (_mock *mockProfileManager) User(ctx context.Context, screenName state.IdentScreenName) (*state.User, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 *state.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (*state.User, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) *state.User); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockProfileManager_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type mockProfileManager_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockProfileManager_Expecter) User(ctx interface{}, screenName interface{}) *mockProfileManager_User_Call {
	return &mockProfileManager_User_Call{Call: _e.mock.On("User", ctx, screenName)}
}

func (_c *mockProfileManager_User_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockProfileManager_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockProfileManager_User_Call) Return(user *state.User, err error) *mockProfileManager_User_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockProfileManager_User_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (*state.User, error)) *mockProfileManager_User_Call {
	_c.Call.Return(run)
	return _c
}
