// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package foodgroup

import (
	"context"

	"github.com/pchchv/go-icq/state"
	"github.com/pchchv/go-icq/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockbuddyBroadcaster creates a new instance of mockbuddyBroadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockbuddyBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockbuddyBroadcaster {
	mock := &mockbuddyBroadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockbuddyBroadcaster is an autogenerated mock type for the buddyBroadcaster type
type mockbuddyBroadcaster struct {
	mock.Mock
}

type mockbuddyBroadcaster_Expecter struct {
	mock *mock.Mock
}

func (_m *mockbuddyBroadcaster) EXPECT() *mockbuddyBroadcaster_Expecter {
	return &mockbuddyBroadcaster_Expecter{mock: &_m.Mock}
}

// BroadcastBuddyArrived provides a mock function for the type mockbuddyBroadcaster
func (_mock *mockbuddyBroadcaster) BroadcastBuddyArrived(ctx context.Context, screenName state.IdentScreenName, userInfo wire.TLVUserInfo) error {
	ret := _mock.Called(ctx, screenName, userInfo)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastBuddyArrived")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, wire.TLVUserInfo) error); ok {
		r0 = returnFunc(ctx, screenName, userInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockbuddyBroadcaster_BroadcastBuddyArrived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastBuddyArrived'
type mockbuddyBroadcaster_BroadcastBuddyArrived_Call struct {
	*mock.Call
}

// BroadcastBuddyArrived is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - userInfo wire.TLVUserInfo
func (_e *mockbuddyBroadcaster_Expecter) BroadcastBuddyArrived(ctx interface{}, screenName interface{}, userInfo interface{}) *mockbuddyBroadcaster_BroadcastBuddyArrived_Call {
	return &mockbuddyBroadcaster_BroadcastBuddyArrived_Call{Call: _e.mock.On("BroadcastBuddyArrived", ctx, screenName, userInfo)}
}

func (_c *mockbuddyBroadcaster_BroadcastBuddyArrived_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, userInfo wire.TLVUserInfo)) *mockbuddyBroadcaster_BroadcastBuddyArrived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 wire.TLVUserInfo
		if args[2] != nil {
			arg2 = args[2].(wire.TLVUserInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbuddyBroadcaster_BroadcastBuddyArrived_Call) Return(err error) *mockbuddyBroadcaster_BroadcastBuddyArrived_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockbuddyBroadcaster_BroadcastBuddyArrived_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, userInfo wire.TLVUserInfo) error) *mockbuddyBroadcaster_BroadcastBuddyArrived_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastBuddyDeparted provides a mock function for the type mockbuddyBroadcaster
func (_mock *mockbuddyBroadcaster) BroadcastBuddyDeparted(ctx context.Context, instance *state.SessionInstance) error {
	ret := _mock.Called(ctx, instance)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastBuddyDeparted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance) error); ok {
		r0 = returnFunc(ctx, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockbuddyBroadcaster_BroadcastBuddyDeparted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastBuddyDeparted'
type mockbuddyBroadcaster_BroadcastBuddyDeparted_Call struct {
	*mock.Call
}

// BroadcastBuddyDeparted is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
func (_e *mockbuddyBroadcaster_Expecter) BroadcastBuddyDeparted(ctx interface{}, instance interface{}) *mockbuddyBroadcaster_BroadcastBuddyDeparted_Call {
	return &mockbuddyBroadcaster_BroadcastBuddyDeparted_Call{Call: _e.mock.On("BroadcastBuddyDeparted", ctx, instance)}
}

func (_c *mockbuddyBroadcaster_BroadcastBuddyDeparted_Call) Run(run func(ctx context.Context, instance *state.SessionInstance)) *mockbuddyBroadcaster_BroadcastBuddyDeparted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbuddyBroadcaster_BroadcastBuddyDeparted_Call) Return(err error) *mockbuddyBroadcaster_BroadcastBuddyDeparted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockbuddyBroadcaster_BroadcastBuddyDeparted_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance) error) *mockbuddyBroadcaster_BroadcastBuddyDeparted_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastVisibility provides a mock function for the type mockbuddyBroadcaster
func (_mock *mockbuddyBroadcaster) BroadcastVisibility(ctx context.Context, you *state.SessionInstance, filter []state.IdentScreenName, sendDepartures bool) error {
	ret := _mock.Called(ctx, you, filter, sendDepartures)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastVisibility")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, []state.IdentScreenName, bool) error); ok {
		r0 = returnFunc(ctx, you, filter, sendDepartures)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockbuddyBroadcaster_BroadcastVisibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastVisibility'
type mockbuddyBroadcaster_BroadcastVisibility_Call struct {
	*mock.Call
}

// BroadcastVisibility is a helper method to define mock.On call
//   - ctx context.Context
//   - you *state.SessionInstance
//   - filter []state.IdentScreenName
//   - sendDepartures bool
func (_e *mockbuddyBroadcaster_Expecter) BroadcastVisibility(ctx interface{}, you interface{}, filter interface{}, sendDepartures interface{}) *mockbuddyBroadcaster_BroadcastVisibility_Call {
	return &mockbuddyBroadcaster_BroadcastVisibility_Call{Call: _e.mock.On("BroadcastVisibility", ctx, you, filter, sendDepartures)}
}

func (_c *mockbuddyBroadcaster_BroadcastVisibility_Call) Run(run func(ctx context.Context, you *state.SessionInstance, filter []state.IdentScreenName, sendDepartures bool)) *mockbuddyBroadcaster_BroadcastVisibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 []state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].([]state.IdentScreenName)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockbuddyBroadcaster_BroadcastVisibility_Call) Return(err error) *mockbuddyBroadcaster_BroadcastVisibility_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockbuddyBroadcaster_BroadcastVisibility_Call) RunAndReturn(run func(ctx context.Context, you *state.SessionInstance, filter []state.IdentScreenName, sendDepartures bool) error) *mockbuddyBroadcaster_BroadcastVisibility_Call {
	_c.Call.Return(run)
	return _c
}
