// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"
	"net/mail"

	"github.com/pchchv/go-icq/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockAccountManager creates a new instance of mockAccountManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAccountManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAccountManager {
	mock := &mockAccountManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAccountManager is an autogenerated mock type for the AccountManager type
type mockAccountManager struct {
	mock.Mock
}

type mockAccountManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAccountManager) EXPECT() *mockAccountManager_Expecter {
	return &mockAccountManager_Expecter{mock: &_m.Mock}
}

// ConfirmStatus provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) ConfirmStatus(ctx context.Context, screenName state.IdentScreenName) (bool, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmStatus")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (bool, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) bool); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAccountManager_ConfirmStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmStatus'
type mockAccountManager_ConfirmStatus_Call struct {
	*mock.Call
}

// ConfirmStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockAccountManager_Expecter) ConfirmStatus(ctx interface{}, screenName interface{}) *mockAccountManager_ConfirmStatus_Call {
	return &mockAccountManager_ConfirmStatus_Call{Call: _e.mock.On("ConfirmStatus", ctx, screenName)}
}

func (_c *mockAccountManager_ConfirmStatus_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockAccountManager_ConfirmStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAccountManager_ConfirmStatus_Call) Return(b bool, err error) *mockAccountManager_ConfirmStatus_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockAccountManager_ConfirmStatus_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (bool, error)) *mockAccountManager_ConfirmStatus_Call {
	_c.Call.Return(run)
	return _c
}

// EmailAddress provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) EmailAddress(ctx context.Context, screenName state.IdentScreenName) (*mail.Address, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for EmailAddress")
	}

	var r0 *mail.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (*mail.Address, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) *mail.Address); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mail.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAccountManager_EmailAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmailAddress'
type mockAccountManager_EmailAddress_Call struct {
	*mock.Call
}

// EmailAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockAccountManager_Expecter) EmailAddress(ctx interface{}, screenName interface{}) *mockAccountManager_EmailAddress_Call {
	return &mockAccountManager_EmailAddress_Call{Call: _e.mock.On("EmailAddress", ctx, screenName)}
}

func (_c *mockAccountManager_EmailAddress_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockAccountManager_EmailAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAccountManager_EmailAddress_Call) Return(address *mail.Address, err error) *mockAccountManager_EmailAddress_Call {
	_c.Call.Return(address, err)
	return _c
}

func (_c *mockAccountManager_EmailAddress_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (*mail.Address, error)) *mockAccountManager_EmailAddress_Call {
	_c.Call.Return(run)
	return _c
}

// RegStatus provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) RegStatus(ctx context.Context, screenName state.IdentScreenName) (uint16, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for RegStatus")
	}

	var r0 uint16
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (uint16, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) uint16); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		r0 = ret.Get(0).(uint16)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAccountManager_RegStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegStatus'
type mockAccountManager_RegStatus_Call struct {
	*mock.Call
}

// RegStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockAccountManager_Expecter) RegStatus(ctx interface{}, screenName interface{}) *mockAccountManager_RegStatus_Call {
	return &mockAccountManager_RegStatus_Call{Call: _e.mock.On("RegStatus", ctx, screenName)}
}

func (_c *mockAccountManager_RegStatus_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockAccountManager_RegStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAccountManager_RegStatus_Call) Return(v uint16, err error) *mockAccountManager_RegStatus_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *mockAccountManager_RegStatus_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (uint16, error)) *mockAccountManager_RegStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetBotStatus provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) SetBotStatus(ctx context.Context, isBot bool, screenName state.IdentScreenName) error {
	ret := _mock.Called(ctx, isBot, screenName)

	if len(ret) == 0 {
		panic("no return value specified for SetBotStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, isBot, screenName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAccountManager_SetBotStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBotStatus'
type mockAccountManager_SetBotStatus_Call struct {
	*mock.Call
}

// SetBotStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - isBot bool
//   - screenName state.IdentScreenName
func (_e *mockAccountManager_Expecter) SetBotStatus(ctx interface{}, isBot interface{}, screenName interface{}) *mockAccountManager_SetBotStatus_Call {
	return &mockAccountManager_SetBotStatus_Call{Call: _e.mock.On("SetBotStatus", ctx, isBot, screenName)}
}

func (_c *mockAccountManager_SetBotStatus_Call) Run(run func(ctx context.Context, isBot bool, screenName state.IdentScreenName)) *mockAccountManager_SetBotStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAccountManager_SetBotStatus_Call) Return(err error) *mockAccountManager_SetBotStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAccountManager_SetBotStatus_Call) RunAndReturn(run func(ctx context.Context, isBot bool, screenName state.IdentScreenName) error) *mockAccountManager_SetBotStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSuspendedStatus provides a mock function for the type mockAccountManager
func (_mock *mockAccountManager) UpdateSuspendedStatus(ctx context.Context, suspendedStatus uint16, screenName state.IdentScreenName) error {
	ret := _mock.Called(ctx, suspendedStatus, screenName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSuspendedStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, suspendedStatus, screenName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAccountManager_UpdateSuspendedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSuspendedStatus'
type mockAccountManager_UpdateSuspendedStatus_Call struct {
	*mock.Call
}

// UpdateSuspendedStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - suspendedStatus uint16
//   - screenName state.IdentScreenName
func (_e *mockAccountManager_Expecter) UpdateSuspendedStatus(ctx interface{}, suspendedStatus interface{}, screenName interface{}) *mockAccountManager_UpdateSuspendedStatus_Call {
	return &mockAccountManager_UpdateSuspendedStatus_Call{Call: _e.mock.On("UpdateSuspendedStatus", ctx, suspendedStatus, screenName)}
}

func (_c *mockAccountManager_UpdateSuspendedStatus_Call) Run(run func(ctx context.Context, suspendedStatus uint16, screenName state.IdentScreenName)) *mockAccountManager_UpdateSuspendedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAccountManager_UpdateSuspendedStatus_Call) Return(err error) *mockAccountManager_UpdateSuspendedStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAccountManager_UpdateSuspendedStatus_Call) RunAndReturn(run func(ctx context.Context, suspendedStatus uint16, screenName state.IdentScreenName) error) *mockAccountManager_UpdateSuspendedStatus_Call {
	_c.Call.Return(run)
	return _c
}
