// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/pchchv/go-icq/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockProfileRetriever creates a new instance of mockProfileRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockProfileRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockProfileRetriever {
	mock := &mockProfileRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockProfileRetriever is an autogenerated mock type for the ProfileRetriever type
type mockProfileRetriever struct {
	mock.Mock
}

type mockProfileRetriever_Expecter struct {
	mock *mock.Mock
}

func (_m *mockProfileRetriever) EXPECT() *mockProfileRetriever_Expecter {
	return &mockProfileRetriever_Expecter{mock: &_m.Mock}
}

// Profile provides a mock function for the type mockProfileRetriever
func (_mock *mockProfileRetriever) Profile(ctx context.Context, screenName state.IdentScreenName) (state.UserProfile, error) {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for Profile")
	}

	var r0 state.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (state.UserProfile, error)); ok {
		return returnFunc(ctx, screenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) state.UserProfile); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		r0 = ret.Get(0).(state.UserProfile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = returnFunc(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockProfileRetriever_Profile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Profile'
type mockProfileRetriever_Profile_Call struct {
	*mock.Call
}

// Profile is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockProfileRetriever_Expecter) Profile(ctx interface{}, screenName interface{}) *mockProfileRetriever_Profile_Call {
	return &mockProfileRetriever_Profile_Call{Call: _e.mock.On("Profile", ctx, screenName)}
}

func (_c *mockProfileRetriever_Profile_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockProfileRetriever_Profile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockProfileRetriever_Profile_Call) Return(userProfile state.UserProfile, err error) *mockProfileRetriever_Profile_Call {
	_c.Call.Return(userProfile, err)
	return _c
}

func (_c *mockProfileRetriever_Profile_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) (state.UserProfile, error)) *mockProfileRetriever_Profile_Call {
	_c.Call.Return(run)
	return _c
}
