// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/pchchv/go-icq/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockBuddyBroadcaster creates a new instance of mockBuddyBroadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBuddyBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBuddyBroadcaster {
	mock := &mockBuddyBroadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockBuddyBroadcaster is an autogenerated mock type for the BuddyBroadcaster type
type mockBuddyBroadcaster struct {
	mock.Mock
}

type mockBuddyBroadcaster_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBuddyBroadcaster) EXPECT() *mockBuddyBroadcaster_Expecter {
	return &mockBuddyBroadcaster_Expecter{mock: &_m.Mock}
}

// BroadcastVisibility provides a mock function for the type mockBuddyBroadcaster
func (_mock *mockBuddyBroadcaster) BroadcastVisibility(ctx context.Context, you *state.SessionInstance, filter []state.IdentScreenName, sendDepartures bool) error {
	ret := _mock.Called(ctx, you, filter, sendDepartures)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastVisibility")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, []state.IdentScreenName, bool) error); ok {
		r0 = returnFunc(ctx, you, filter, sendDepartures)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyBroadcaster_BroadcastVisibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastVisibility'
type mockBuddyBroadcaster_BroadcastVisibility_Call struct {
	*mock.Call
}

// BroadcastVisibility is a helper method to define mock.On call
//   - ctx context.Context
//   - you *state.SessionInstance
//   - filter []state.IdentScreenName
//   - sendDepartures bool
func (_e *mockBuddyBroadcaster_Expecter) BroadcastVisibility(ctx interface{}, you interface{}, filter interface{}, sendDepartures interface{}) *mockBuddyBroadcaster_BroadcastVisibility_Call {
	return &mockBuddyBroadcaster_BroadcastVisibility_Call{Call: _e.mock.On("BroadcastVisibility", ctx, you, filter, sendDepartures)}
}

func (_c *mockBuddyBroadcaster_BroadcastVisibility_Call) Run(run func(ctx context.Context, you *state.SessionInstance, filter []state.IdentScreenName, sendDepartures bool)) *mockBuddyBroadcaster_BroadcastVisibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 []state.IdentScreenName
		if args[2] != nil {
			arg2 = args[2].([]state.IdentScreenName)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockBuddyBroadcaster_BroadcastVisibility_Call) Return(err error) *mockBuddyBroadcaster_BroadcastVisibility_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyBroadcaster_BroadcastVisibility_Call) RunAndReturn(run func(ctx context.Context, you *state.SessionInstance, filter []state.IdentScreenName, sendDepartures bool) error) *mockBuddyBroadcaster_BroadcastVisibility_Call {
	_c.Call.Return(run)
	return _c
}
